name: My GitHub Action

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
          uses: actions/checkout@v1

      - name: Set Up JDK
          uses: actions/setup-java@v2
          with:
            java-version: 1.8

      - name: Change wrapper permissions
          run: chmod +x ./gradlew

      - name: Run Tests
          run: ./gradlew test

      - name: Build Project
          run: ./gradlew assemble

